[default]
extend-ignore-re = [
  # Ignore `files = "";` declarations
  "(?Rm)^\\s*files\\s*=.*;$"
]

[default.extend-words]
edn = "edn"             # `cljfmt` option
mosquitto = "mosquitto" # `typos` example
